"""Fixed, pre-approved wording for safety situations. Never generated by the model."""

from __future__ import annotations

from dataclasses import dataclass

from carecompanion.profile import HospitalProfile


@dataclass(frozen=True, slots=True)
class SafetyMessages:
    emergency: str
    crisis: str
    injection: str
    output_fallback: str

    @classmethod
    def from_profile(cls, profile: HospitalProfile) -> SafetyMessages:
        c = profile.contacts
        return cls(
            emergency=(
                f"This could be an emergency. Please call {c['emergency']} now, or go to your "
                f"nearest A&E. If you are not in immediate danger but need urgent medical "
                f"advice, call {c['urgent_advice']}. I can't give medical advice, but once "
                f"you are safe I'm happy to help with hospital services."
            ),
            crisis=(
                f"I'm really sorry you're going through this, and I'm glad you told me. You "
                f"don't have to face it alone. If you might act on these thoughts, or you are "
                f"in danger right now, please call {c['emergency']} or go to your nearest A&E. "
                f"You can also talk to {c['crisis_line']} at any time, free of charge, or call "
                f"{c['urgent_advice']} and choose the mental health option."
            ),
            injection=(
                "I can only help with hospital services, such as appointments, visiting times "
                "and discharge paperwork, and I can't change how I work. Is there something "
                "like that I can help you with?"
            ),
            output_fallback=(
                f"I'm sorry, I can't confirm that. Please call the Patient Advice Team on "
                f"{c['patient_advice_team']}. If it is an emergency, call {c['emergency']}."
            ),
        )
